### PR TITLE
Add did key errors to spec.

### PR DESCRIPTION
**Pull request by aljones15**
Adds errors from the [did key spec](https://w3c-ccg.github.io/did-method-key/) to the did resolution.

Errors added:

- invalidPublicKeyLength
- invalidPublicKey
- invalidDidUrl
- unsupportedPublicKeyType
- invalidPublicKeyType

### CODE REVIEW

**Review by msporny — APPROVED** [review]

**Review by peacekeeper — APPROVED** [review]
Looks useful!

**Comment by peacekeeper** [comment]
The only issue I see is that "invalidDidUrl" is [already defined in DID Core](https://www.w3.org/TR/did-core/#did-url-dereferencing-metadata), so either we don't define it here in DID Resolution, OR we include all DID Core errors also in DID Resolution (and potentially add more details).

**Comment by aljones15** [comment]
@peacekeeper the existing file:///home/liminal18/Programs/nodejs/w3c/did-core/index.html#did-resolution-metadata errors are actually kind of small, so I think we should add them to this section with more specific instructions on when to throw. We should link back to did core so it is known those errors are did core and not specific to did key or did resolution. That is my idea, but consensus could vary. @msporny ideas here?

**Comment by peacekeeper** [comment]
> I think we should add them to this section with more specific instructions on when to throw.

I agree this would be a good idea. Do you want to add that now, or later? Maybe first merge this PR here? (why is it still draft?)

**Comment by aljones15** [comment]
> > I think we should add them to this section with more specific instructions on when to throw.
> 
> I agree this would be a good idea. Do you want to add that now, or later? Maybe first merge this PR here? (why is it still draft?)

Sorry about the delay, but I got massively delayed last week by some more pressing stuff. I will add the did-core stuff today.

**Review by peacekeeper — APPROVED** [review]

**Comment by peacekeeper** [comment]
@aljones15 I merged this, and note that I added a few other commits on top of it:
- https://github.com/w3c-ccg/did-resolution/commit/d210f527a407e65712eb5cca40f321993a141265 and https://github.com/w3c-ccg/did-resolution/commit/36f4dd1565427a0f6003d93cbbb68233fa8386a6to improve references to the DID Core sections.
- https://github.com/w3c-ccg/did-resolution/commit/b7079295472a7bfa7cb9419d5ecd5911727c1be5 to re-arrange errors to make DID Core errors show up on top
- https://github.com/w3c-ccg/did-resolution/commit/7b7c2dcdbefb1fdf21b788f8c1fda63185851905 to add representationNotSupported. You're right that DID Resolution currently doesn't talk about it, but it should, and therefore (to be consistent) I think it's best to list all DID Core errors also in DID Resolution.

**Pull request merged**
