### PR TITLE
Add context

### PR DESCRIPTION
**Pull request by OR13**
`"@context": "https://www.w3.org/ns/did-resolution/v1",`

- [x] w3id.org PR merged https://github.com/perma-id/w3id.org/pull/1855

When this is merged, this will work: https://w3id.org/did-resolution/v1

### CODE REVIEW

**Comment by peacekeeper** [comment]
@OR13 thanks this is great. I added a few more commits on top of yours. Do you agree with them? If yes I think we can merge.

**Review by peacekeeper — APPROVED** [review]

**Comment by OR13** [comment]
awesome, merge when ready.

**Review by kdenhartog — APPROVED** [review]

**Comment by peacekeeper** [comment]
I put this on the agenda for today's DID Resolution call: https://docs.google.com/document/d/1qYBaXQMUoB86Alquu7WBtWOxsS8SMhp1fioYKEGCabE/

**Comment by dmitrizagidulin** [comment]
👍  awesome.

**Pull request merged**
